///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace YosuvaCom.BusinessModules.Custom
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LoginWithCustomAction recording.
    /// </summary>
    [TestModule("66ab641c-63cb-4d46-9c23-d1fed84e9889", ModuleType.Recording, 1)]
    public partial class LoginWithCustomAction : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::YosuvaCom.YosuvaComRepository repository.
        /// </summary>
        public static global::YosuvaCom.YosuvaComRepository repo = global::YosuvaCom.YosuvaComRepository.Instance;

        static LoginWithCustomAction instance = new LoginWithCustomAction();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LoginWithCustomAction()
        {
            FirstName = "yourtext";
            LastName = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LoginWithCustomAction Instance
        {
            get { return instance; }
        }

#region Variables

        string _FirstName;

        /// <summary>
        /// Gets or sets the value of variable FirstName.
        /// </summary>
        [TestVariable("74b8396e-ce6c-41dc-8054-52f1691d62d0")]
        public string FirstName
        {
            get { return _FirstName; }
            set { _FirstName = value; }
        }

        string _LastName;

        /// <summary>
        /// Gets or sets the value of variable LastName.
        /// </summary>
        [TestVariable("dd9a6192-b592-43ed-b181-ce7bd58fe571")]
        public string LastName
        {
            get { return _LastName; }
            set { _LastName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Framework.Actions.Type(repo.YosuvaCom.First_NameInfo, FirstName);
            Delay.Milliseconds(0);
            
            Framework.Actions.Type(repo.YosuvaCom.Last_NameInfo, LastName);
            Delay.Milliseconds(0);
            
            Framework.Actions.Click(repo.YosuvaCom.SubmitInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
