///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace YosuvaCom.BusinessModules
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LoginSimpleData recording.
    /// </summary>
    [TestModule("0bdcba98-7125-407d-9fca-514d6898d223", ModuleType.Recording, 1)]
    public partial class LoginSimpleData : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::YosuvaCom.YosuvaComRepository repository.
        /// </summary>
        public static global::YosuvaCom.YosuvaComRepository repo = global::YosuvaCom.YosuvaComRepository.Instance;

        static LoginSimpleData instance = new LoginSimpleData();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LoginSimpleData()
        {
            FirstName = "yourtext";
            LastName = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LoginSimpleData Instance
        {
            get { return instance; }
        }

#region Variables

        string _FirstName;

        /// <summary>
        /// Gets or sets the value of variable FirstName.
        /// </summary>
        [TestVariable("0a2ce98a-d383-4063-95d2-e089b0446286")]
        public string FirstName
        {
            get { return _FirstName; }
            set { _FirstName = value; }
        }

        string _LastName;

        /// <summary>
        /// Gets or sets the value of variable LastName.
        /// </summary>
        [TestVariable("c97654f5-390f-4312-b875-57a850f65260")]
        public string LastName
        {
            get { return _LastName; }
            set { _LastName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$FirstName' with focus on 'YosuvaCom.First_Name'.", repo.YosuvaCom.First_NameInfo, new RecordItemIndex(0));
            repo.YosuvaCom.First_Name.PressKeys(FirstName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$LastName' with focus on 'YosuvaCom.Last_Name'.", repo.YosuvaCom.Last_NameInfo, new RecordItemIndex(1));
            repo.YosuvaCom.Last_Name.PressKeys(LastName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'YosuvaCom.Submit' at Center.", repo.YosuvaCom.SubmitInfo, new RecordItemIndex(2));
            repo.YosuvaCom.Submit.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
